version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - "5672:5672"   # Porta padrão do AMQP
      - "15672:15672" # Porta da interface de gerenciamento (web)
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
